# Generated by Django 4.0.4 on 2022-04-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBMS_App', '0002_employee1'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('beds', models.CharField(max_length=20)),
                ('ac', models.CharField(max_length=20)),
                ('flr', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=20)),
            ],
        ),
    ]
