# Generated by Django 4.0.4 on 2022-04-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBMS_App', '0003_rooms1'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkin_checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('profe', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('id_prof', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=25)),
                ('adult', models.CharField(max_length=10)),
                ('children', models.CharField(max_length=10)),
                ('arrival', models.CharField(max_length=20)),
                ('depurt', models.CharField(max_length=20)),
                ('room_num', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('beds', models.CharField(max_length=20)),
                ('ac', models.CharField(max_length=20)),
                ('flr', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=20)),
                ('tcost', models.CharField(max_length=20)),
                ('pmod', models.CharField(max_length=20)),
                ('dmod', models.CharField(max_length=20)),
                ('checkby', models.CharField(max_length=20)),
            ],
        ),
    ]
