# Generated by Django 4.0.4 on 2022-04-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBMS_App', '0005_checkin_checkout_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin_checkout',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
    ]
