# Generated by Django 4.0.4 on 2022-04-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBMS_App', '0006_checkin_checkout_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin_checkout',
            name='dob2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin_checkout',
            name='id_number2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin_checkout',
            name='id_prof2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin_checkout',
            name='material2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin_checkout',
            name='name2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin_checkout',
            name='phone2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin_checkout',
            name='profe2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin_checkout',
            name='rel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
