# Generated by Django 4.0.4 on 2022-04-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBMS_App', '0007_checkin_checkout_dob2_checkin_checkout_id_number2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin_checkout',
            name='gender2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
