# Generated by Django 4.0.4 on 2022-04-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBMS_App', '0008_checkin_checkout_gender2'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin_checkout',
            name='checkin_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
