# Generated by Django 4.0.4 on 2022-04-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBMS_App', '0009_checkin_checkout_checkin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin_checkout',
            name='emp_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
