# Generated by Django 4.0.4 on 2022-04-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBMS_App', '0010_checkin_checkout_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin_checkout',
            name='arrival',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='checkin_checkout',
            name='depurt',
            field=models.DateField(default=''),
        ),
    ]
